# Generated by Django 4.0.4 on 2022-04-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroesApiRest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hero',
            name='copyright',
            field=models.CharField(default='© 2022 MARVEL', max_length=15),
        ),
    ]
